### ISSUE TITLE
Modeling Design Patterns 

### ISSUE THREAD

**Issue by pdelgosha22** [open223/docs.open223.info#16]
@MatthewSteen I have added figures subdirectory under guides. Feel free to move it somewhere else.
@lazlop Do you still want to keep the text you have added for this section
@steveraysteveray Feel free to edit my text

**Comment by steveraysteveray** [comment]
I'm not seeing any subdirectory under guides...

**Comment by MatthewSteen** [comment]
@pdelgosha22 a few comments...

1. If you don't put any files in a folder it doesn't show up here. It's common practice to put an _empty_ `.gitkeep` file in a folder to initialize it.

2. I suggest naming it `images`, or maybe we have both per the Sphinx docs, which distinguishes between the two. https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives
- image (see also Images below)
- figure (an image with caption and optional legend)

3. The #1 issue is a place to discuss the overall content (files/pages) for the Guides section. I think we should then have a dedicated issue and PR for each one, like this one 👍🏻

**Comment by lazlop** [comment]
No need to keep any text! That was all just outlining/placeholder.

**Comment by MatthewSteen** [comment]
I wonder if this is a better fit for the _first_ tutorial if it's introducing the ontology in a more detail than the `explanation/223.md`, which would be a natural second page. Then the _second_ tutorial would actually begin working with a model with Python.

**Comment by MatthewSteen** [comment]
> I wonder if this is a better fit for the _first_ tutorial if it's introducing the ontology in a more detail than the `explanation/223.md`, which would be a natural second page. Then the _second_ tutorial would actually begin working with a model with Python.

We agreed that this should remain in Guides as discussed in our meeting today.
